! include/mpcci_quantities.inc
! 
! This file was automatically generated by the Perl script "qc"
!    Source file: "mpcci_quantities.def"
!    Compiled by: pbayrasy@catalan, Wed May  6 17:47:43 2015
! 
! Quantity id (QID) definitions: The QID consists of the ...
!       - dimension                (DIM) [1...64]
!       - interpolation            (IOK) [0... 1]
!       - extrapolation            (XOK) [0... 1]
!       - field interpolation type (INT) [1...15]
!       - physical meaning         (PHY) [1...15]
!       - 4 validity bits          (VAL) : 0=global, quantity valid for Volume/Face/Line/Point coupling
!       - tensor order             (ORD) [0... 7] 0=scalar/1=vector/2=tensor/3=3dr order tensor...
!       - ramping                  (ROK) [0... 1]
!       - signature                (SIG) [0..255]
!    and is specified within a single unsigned.
! 
!    nibbles: |0000|0000|0|000|0000|0000|0000|00|00|0000|
!             |---SIG---|R|ORD|-PHY|-VAL|-INT|XI|---DIM-|
! 
!    $Id: mpcci_quantities.f90 1568 2015-05-06 15:51:33Z pbayrasy $
!


! Control switch(Int) (IntFlag:0x01000b01)
       INTEGER   MPCCI_QID_INT_SWITCH
       PARAMETER(MPCCI_QID_INT_SWITCH=X'01000b01')

! Control switch(Real) (RealFlag:0x02000b01)
       INTEGER   MPCCI_QID_REAL_SWITCH
       PARAMETER(MPCCI_QID_REAL_SWITCH=X'02000b01')

! Physical time (PhysicalTime:0x03000a01)
       INTEGER   MPCCI_QID_PHYSICAL_TIME
       PARAMETER(MPCCI_QID_PHYSICAL_TIME=X'03000a01')

! Time step size (DeltaTime:0x04000a01)
       INTEGER   MPCCI_QID_TIMESTEP_SIZE
       PARAMETER(MPCCI_QID_TIMESTEP_SIZE=X'04000a01')

! Time step number (TimeStepNo:0x05000b01)
       INTEGER   MPCCI_QID_TIMESTEP_COUNT
       PARAMETER(MPCCI_QID_TIMESTEP_COUNT=X'05000b01')

! Iteration number (IterationNo:0x06000b01)
       INTEGER   MPCCI_QID_ITERATION_COUNT
       PARAMETER(MPCCI_QID_ITERATION_COUNT=X'06000b01')

! Global residual (Residual:0x07000b01)
       INTEGER   MPCCI_QID_GLOBAL_RESIDUAL
       PARAMETER(MPCCI_QID_GLOBAL_RESIDUAL=X'07000b01')

! Reference pressure (RefPressure:0x0b000b01)
       INTEGER   MPCCI_QID_REF_PRESSURE
       PARAMETER(MPCCI_QID_REF_PRESSURE=X'0b000b01')

! Electric voltage - phase 1 (Voltage1:0x15000b01)
       INTEGER   MPCCI_QID_VOLTAGE1
       PARAMETER(MPCCI_QID_VOLTAGE1=X'15000b01')

! Electric voltage - phase 2 (Voltage2:0x16000b01)
       INTEGER   MPCCI_QID_VOLTAGE2
       PARAMETER(MPCCI_QID_VOLTAGE2=X'16000b01')

! Electric voltage - phase 3 (Voltage3:0x17000b01)
       INTEGER   MPCCI_QID_VOLTAGE3
       PARAMETER(MPCCI_QID_VOLTAGE3=X'17000b01')

! Electric voltage - phase 4 (Voltage4:0x18000b01)
       INTEGER   MPCCI_QID_VOLTAGE4
       PARAMETER(MPCCI_QID_VOLTAGE4=X'18000b01')

! Electric current - phase 1 (Current1:0x19000b01)
       INTEGER   MPCCI_QID_CURRENT1
       PARAMETER(MPCCI_QID_CURRENT1=X'19000b01')

! Electric current - phase 2 (Current2:0x1a000b01)
       INTEGER   MPCCI_QID_CURRENT2
       PARAMETER(MPCCI_QID_CURRENT2=X'1a000b01')

! Electric current - phase 3 (Current3:0x1b000b01)
       INTEGER   MPCCI_QID_CURRENT3
       PARAMETER(MPCCI_QID_CURRENT3=X'1b000b01')

! Electric current - phase 4 (Current4:0x1c000b01)
       INTEGER   MPCCI_QID_CURRENT4
       PARAMETER(MPCCI_QID_CURRENT4=X'1c000b01')

! Moving obstacle CG position (CGPosition:0x1f170b03)
       INTEGER   MPCCI_QID_MO_POSITION
       PARAMETER(MPCCI_QID_MO_POSITION=X'1f170b03')

! Moving obstacle CG angle (CGAngle:0x20170b03)
       INTEGER   MPCCI_QID_MO_ANGLE
       PARAMETER(MPCCI_QID_MO_ANGLE=X'20170b03')

! Moving obstacle CG velocity (CGVelocity:0x21150b03)
       INTEGER   MPCCI_QID_MO_VELOCITY
       PARAMETER(MPCCI_QID_MO_VELOCITY=X'21150b03')

! Moving obstacle CG angular velocity (CGOmega:0x22150b03)
       INTEGER   MPCCI_QID_MO_OMEGA
       PARAMETER(MPCCI_QID_MO_OMEGA=X'22150b03')

! Global scalar 00 (gs00:0x28000b01)
       INTEGER   MPCCI_QID_UGS_00
       PARAMETER(MPCCI_QID_UGS_00=X'28000b01')

! Global scalar 01 (gs01:0x29000b01)
       INTEGER   MPCCI_QID_UGS_01
       PARAMETER(MPCCI_QID_UGS_01=X'29000b01')

! Global scalar 02 (gs02:0x2a000b01)
       INTEGER   MPCCI_QID_UGS_02
       PARAMETER(MPCCI_QID_UGS_02=X'2a000b01')

! Global scalar 03 (gs03:0x2b000b01)
       INTEGER   MPCCI_QID_UGS_03
       PARAMETER(MPCCI_QID_UGS_03=X'2b000b01')

! Global scalar 04 (gs04:0x2c000b01)
       INTEGER   MPCCI_QID_UGS_04
       PARAMETER(MPCCI_QID_UGS_04=X'2c000b01')

! Global scalar 05 (gs05:0x2d000b01)
       INTEGER   MPCCI_QID_UGS_05
       PARAMETER(MPCCI_QID_UGS_05=X'2d000b01')

! Global scalar 06 (gs06:0x2e000b01)
       INTEGER   MPCCI_QID_UGS_06
       PARAMETER(MPCCI_QID_UGS_06=X'2e000b01')

! Global scalar 07 (gs07:0x2f000b01)
       INTEGER   MPCCI_QID_UGS_07
       PARAMETER(MPCCI_QID_UGS_07=X'2f000b01')

! Global vector 00 (gv00:0x28100b03)
       INTEGER   MPCCI_QID_UGV_00
       PARAMETER(MPCCI_QID_UGV_00=X'28100b03')

! Global vector 01 (gv01:0x29100b03)
       INTEGER   MPCCI_QID_UGV_01
       PARAMETER(MPCCI_QID_UGV_01=X'29100b03')

! Global vector 02 (gv02:0x2a100b03)
       INTEGER   MPCCI_QID_UGV_02
       PARAMETER(MPCCI_QID_UGV_02=X'2a100b03')

! Global vector 03 (gv03:0x2b100b03)
       INTEGER   MPCCI_QID_UGV_03
       PARAMETER(MPCCI_QID_UGV_03=X'2b100b03')

! Global vector 04 (gv04:0x2c100b03)
       INTEGER   MPCCI_QID_UGV_04
       PARAMETER(MPCCI_QID_UGV_04=X'2c100b03')

! Global vector 05 (gv05:0x2d100b03)
       INTEGER   MPCCI_QID_UGV_05
       PARAMETER(MPCCI_QID_UGV_05=X'2d100b03')

! Global vector 06 (gv06:0x2e100b03)
       INTEGER   MPCCI_QID_UGV_06
       PARAMETER(MPCCI_QID_UGV_06=X'2e100b03')

! Global vector 07 (gv07:0x2f100b03)
       INTEGER   MPCCI_QID_UGV_07
       PARAMETER(MPCCI_QID_UGV_07=X'2f100b03')

! Boundary temperature (WallTemp:0x018562c1)
       INTEGER   MPCCI_QID_WALLTEMPERATURE
       PARAMETER(MPCCI_QID_WALLTEMPERATURE=X'018562c1')

! Boundary normal heat flux density (WallHeatFlux:0x028664c1)
       INTEGER   MPCCI_QID_WALLHEATFLUX
       PARAMETER(MPCCI_QID_WALLHEATFLUX=X'028664c1')

! Boundary heat transfer coefficient (WallHTCoeff:0x038562c1)
       INTEGER   MPCCI_QID_WALLHTCOEFF
       PARAMETER(MPCCI_QID_WALLHTCOEFF=X'038562c1')

! Film temperature (FilmTemp:0x048562c1)
       INTEGER   MPCCI_QID_FILMTEMPERATURE
       PARAMETER(MPCCI_QID_FILMTEMPERATURE=X'048562c1')

! Heat rate (HeatRate:0x0585f3c1)
       INTEGER   MPCCI_QID_HEATRATE
       PARAMETER(MPCCI_QID_HEATRATE=X'0585f3c1')

! Boundary absolute force vector (WallForce:0x0a9563c3)
       INTEGER   MPCCI_QID_WALLFORCE
       PARAMETER(MPCCI_QID_WALLFORCE=X'0a9563c3')

! Boundary relative force vector (RelWallForce:0x0b9563c3)
       INTEGER   MPCCI_QID_RELWALLFORCE
       PARAMETER(MPCCI_QID_RELWALLFORCE=X'0b9563c3')

! Temperature (Temperature:0x1585f2c1)
       INTEGER   MPCCI_QID_TEMPERATURE
       PARAMETER(MPCCI_QID_TEMPERATURE=X'1585f2c1')

! Total Temperature (TotalTemp:0x1685e2c1)
       INTEGER   MPCCI_QID_TOTALTEMP
       PARAMETER(MPCCI_QID_TOTALTEMP=X'1685e2c1')

! Absolute pressure (AbsPressure:0x1f85e4c1)
       INTEGER   MPCCI_QID_ABSPRESSURE
       PARAMETER(MPCCI_QID_ABSPRESSURE=X'1f85e4c1')

! Relative pressure (OverPressure:0x2085e4c1)
       INTEGER   MPCCI_QID_OVERPRESSURE
       PARAMETER(MPCCI_QID_OVERPRESSURE=X'2085e4c1')

! Pore pressure (PorePressure:0x2185e4c1)
       INTEGER   MPCCI_QID_POREPRESSURE
       PARAMETER(MPCCI_QID_POREPRESSURE=X'2185e4c1')

! Acoustic pressure (AcstPressure:0x2285e4c1)
       INTEGER   MPCCI_QID_ACSTPRESSURE
       PARAMETER(MPCCI_QID_ACSTPRESSURE=X'2285e4c1')

! Total pressure (TotalPressure:0x2385f4c1)
       INTEGER   MPCCI_QID_TOTALPRESSURE
       PARAMETER(MPCCI_QID_TOTALPRESSURE=X'2385f4c1')

! Dynamic pressure (DynPressure:0x2485e4c1)
       INTEGER   MPCCI_QID_DYNPRESSURE
       PARAMETER(MPCCI_QID_DYNPRESSURE=X'2485e4c1')

! Static pressure (StaticPressure:0x2585f4c1)
       INTEGER   MPCCI_QID_STATICPRESSURE
       PARAMETER(MPCCI_QID_STATICPRESSURE=X'2585f4c1')

! Velocity vector (Velocity:0x2995f2c3)
       INTEGER   MPCCI_QID_VELOCITY
       PARAMETER(MPCCI_QID_VELOCITY=X'2995f2c3')

! Acceleration vector (Acceleration:0x2a95f2c3)
       INTEGER   MPCCI_QID_ACCELERATION
       PARAMETER(MPCCI_QID_ACCELERATION=X'2a95f2c3')

! Velocity magnitude (VelocityMagnitude:0x2b85f2c1)
       INTEGER   MPCCI_QID_VELOCITYMAG
       PARAMETER(MPCCI_QID_VELOCITYMAG=X'2b85f2c1')

! Angular coordinate (AngularCoordinate:0x2c971143)
       INTEGER   MPCCI_QID_ANGULARCOORD
       PARAMETER(MPCCI_QID_ANGULARCOORD=X'2c971143')

! Angular velocity (AngularVelocity:0x2d951243)
       INTEGER   MPCCI_QID_ANGULARVELOCITY
       PARAMETER(MPCCI_QID_ANGULARVELOCITY=X'2d951243')

! Angular acceleration (AngularAcceleration:0x2e951243)
       INTEGER   MPCCI_QID_ANGULARACCELERATION
       PARAMETER(MPCCI_QID_ANGULARACCELERATION=X'2e951243')

! Pore fluid flow (PorousFlow:0x3106c4c1)
       INTEGER   MPCCI_QID_POREFLOW
       PARAMETER(MPCCI_QID_POREFLOW=X'3106c4c1')

! General body force density vector (BodyForce:0x339284c3)
       INTEGER   MPCCI_QID_BODYFORCE
       PARAMETER(MPCCI_QID_BODYFORCE=X'339284c3')

! Lorentz force density vector (LorentzForce:0x349284c3)
       INTEGER   MPCCI_QID_LORENTZFORCE
       PARAMETER(MPCCI_QID_LORENTZFORCE=X'349284c3')

! Force (Force:0x3592f3c3)
       INTEGER   MPCCI_QID_FORCE
       PARAMETER(MPCCI_QID_FORCE=X'3592f3c3')

! Torque (Torque:0x3692f3c3)
       INTEGER   MPCCI_QID_TORQUE
       PARAMETER(MPCCI_QID_TORQUE=X'3692f3c3')

! Heat flux density vector (HeatFlux:0x3d1684c3)
       INTEGER   MPCCI_QID_HEATFLUX
       PARAMETER(MPCCI_QID_HEATFLUX=X'3d1684c3')

! General heat source density (HeatSource:0x3e0384c1)
       INTEGER   MPCCI_QID_HEATSOURCE
       PARAMETER(MPCCI_QID_HEATSOURCE=X'3e0384c1')

! Enthalpy density (Enthalpy:0x3f0084c1)
       INTEGER   MPCCI_QID_ENTHALPY
       PARAMETER(MPCCI_QID_ENTHALPY=X'3f0084c1')

! Joule heat density (JouleHeat:0x400384c1)
       INTEGER   MPCCI_QID_JOULEHEAT
       PARAMETER(MPCCI_QID_JOULEHEAT=X'400384c1')

! Joule heat linearization (JouleHeatLin:0x410384c1)
       INTEGER   MPCCI_QID_JOULEHEATLIN
       PARAMETER(MPCCI_QID_JOULEHEATLIN=X'410384c1')

! Volume flow vector (VolumeFlow:0x471183c3)
       INTEGER   MPCCI_QID_VOLFLOWVECT
       PARAMETER(MPCCI_QID_VOLFLOWVECT=X'471183c3')

! Volume flow rate (VolumeFlowRate:0x480153c1)
       INTEGER   MPCCI_QID_VOLFLOWRATE
       PARAMETER(MPCCI_QID_VOLFLOWRATE=X'480153c1')

! Mass flow vector (MassFlowVect:0x491183c3)
       INTEGER   MPCCI_QID_MASSFLOWVECT
       PARAMETER(MPCCI_QID_MASSFLOWVECT=X'491183c3')

! Mass flow rate (MassFlowRate:0x4a0153c1)
       INTEGER   MPCCI_QID_MASSFLOWRATE
       PARAMETER(MPCCI_QID_MASSFLOWRATE=X'4a0153c1')

! Mass flux vector (MassFluxVect:0x4b1184c3)
       INTEGER   MPCCI_QID_MASSFLUXVECT
       PARAMETER(MPCCI_QID_MASSFLUXVECT=X'4b1184c3')

! Mass flux rate (MassFluxRate:0x4c0154c1)
       INTEGER   MPCCI_QID_MASSFLUXRATE
       PARAMETER(MPCCI_QID_MASSFLUXRATE=X'4c0154c1')

! Nodal position (NPosition:0x5297e143)
       INTEGER   MPCCI_QID_NPOSITION
       PARAMETER(MPCCI_QID_NPOSITION=X'5297e143')

! Point position (PointPosition:0x54971143)
       INTEGER   MPCCI_QID_POINTPOSITION
       PARAMETER(MPCCI_QID_POINTPOSITION=X'54971143')

! Electric current density vector (CurrentDensity:0x5b16e4c3)
       INTEGER   MPCCI_QID_CURRENTDENSITY
       PARAMETER(MPCCI_QID_CURRENTDENSITY=X'5b16e4c3')

! Magnetic flux density vector (MagneticFlux:0x5c16e4c3)
       INTEGER   MPCCI_QID_MAGNETICFLUX
       PARAMETER(MPCCI_QID_MAGNETICFLUX=X'5c16e4c3')

! Magnetic field vector (MagneticField:0x5d16e2c3)
       INTEGER   MPCCI_QID_MAGNETICFIELD
       PARAMETER(MPCCI_QID_MAGNETICFIELD=X'5d16e2c3')

! Electric flux vector (ElectricFlux:0x5e16e4c3)
       INTEGER   MPCCI_QID_ELECTRICFLUX
       PARAMETER(MPCCI_QID_ELECTRICFLUX=X'5e16e4c3')

! Electric field vector (ElectricField:0x5f16e2c3)
       INTEGER   MPCCI_QID_ELECTRICFIELD
       PARAMETER(MPCCI_QID_ELECTRICFIELD=X'5f16e2c3')

! Charge density (ChargeDensity:0x6000e2c1)
       INTEGER   MPCCI_QID_CHARGEDENSITY
       PARAMETER(MPCCI_QID_CHARGEDENSITY=X'6000e2c1')

! Electric Potential (ElectricPot:0x6105e2c1)
       INTEGER   MPCCI_QID_ELECTRICPOT
       PARAMETER(MPCCI_QID_ELECTRICPOT=X'6105e2c1')

! Density (Density:0x650482c1)
       INTEGER   MPCCI_QID_DENSITY
       PARAMETER(MPCCI_QID_DENSITY=X'650482c1')

! Specific heat (SpecificHeat:0x660482c1)
       INTEGER   MPCCI_QID_SPECHEAT
       PARAMETER(MPCCI_QID_SPECHEAT=X'660482c1')

! Thermal conductivity - x (ThermCondX:0x6f04e2c1)
       INTEGER   MPCCI_QID_THERMCONDX
       PARAMETER(MPCCI_QID_THERMCONDX=X'6f04e2c1')

! Thermal conductivity - y (ThermCondY:0x7004e2c1)
       INTEGER   MPCCI_QID_THERMCONDY
       PARAMETER(MPCCI_QID_THERMCONDY=X'7004e2c1')

! Thermal conductivity - z (ThermCondZ:0x7104e2c1)
       INTEGER   MPCCI_QID_THERMCONDZ
       PARAMETER(MPCCI_QID_THERMCONDZ=X'7104e2c1')

! Thermal conductivity - xyz (ThermCond1:0x7204e2c1)
       INTEGER   MPCCI_QID_THERMCOND1
       PARAMETER(MPCCI_QID_THERMCOND1=X'7204e2c1')

! Thermal conductivity -(x,y,z) (ThermCond3:0x7314e2c3)
       INTEGER   MPCCI_QID_THERMCOND3
       PARAMETER(MPCCI_QID_THERMCOND3=X'7314e2c3')

! Electric conductivity - x (ElectrCondX:0x7904e2c1)
       INTEGER   MPCCI_QID_ELECTCONDX
       PARAMETER(MPCCI_QID_ELECTCONDX=X'7904e2c1')

! Electric conductivity - y (ElectrCondY:0x7a04e2c1)
       INTEGER   MPCCI_QID_ELECTCONDY
       PARAMETER(MPCCI_QID_ELECTCONDY=X'7a04e2c1')

! Electric conductivity - z (ElectrCondZ:0x7b04e2c1)
       INTEGER   MPCCI_QID_ELECTCONDZ
       PARAMETER(MPCCI_QID_ELECTCONDZ=X'7b04e2c1')

! Electric conductivity - xyz (ElectrCond1:0x7c04e2c1)
       INTEGER   MPCCI_QID_ELECTCOND1
       PARAMETER(MPCCI_QID_ELECTCOND1=X'7c04e2c1')

! Electric conductivity - (x,y,z) (ElectrCond3:0x7d14e2c3)
       INTEGER   MPCCI_QID_ELECTCOND3
       PARAMETER(MPCCI_QID_ELECTCOND3=X'7d14e2c3')

! Electric resistivity - x (ElectrResX:0x8304e2c1)
       INTEGER   MPCCI_QID_ELECTRESVX
       PARAMETER(MPCCI_QID_ELECTRESVX=-2096831807)

! Electric resistivity - y (ElectrResY:0x8404e2c1)
       INTEGER   MPCCI_QID_ELECTRESVY
       PARAMETER(MPCCI_QID_ELECTRESVY=-2080054591)

! Electric resistivity - z (ElectrResZ:0x8504e2c1)
       INTEGER   MPCCI_QID_ELECTRESVZ
       PARAMETER(MPCCI_QID_ELECTRESVZ=-2063277375)

! Electric resistivity - xyz (ElectrRes1:0x8604e2c1)
       INTEGER   MPCCI_QID_ELECTRESV1
       PARAMETER(MPCCI_QID_ELECTRESV1=-2046500159)

! Electric resistivity - (x,y,z) (ElectrRes3:0x8714e2c3)
       INTEGER   MPCCI_QID_ELECTRESV3
       PARAMETER(MPCCI_QID_ELECTRESV3=-2028674365)

! Species mass fraction 00 (YI00:0x0a08e2c1)
       INTEGER   MPCCI_QID_YI_00
       PARAMETER(MPCCI_QID_YI_00=X'0a08e2c1')

! Species mass fraction 01 (YI01:0x0b08e2c1)
       INTEGER   MPCCI_QID_YI_01
       PARAMETER(MPCCI_QID_YI_01=X'0b08e2c1')

! Species mass fraction 02 (YI02:0x0c08e2c1)
       INTEGER   MPCCI_QID_YI_02
       PARAMETER(MPCCI_QID_YI_02=X'0c08e2c1')

! Species mass fraction 03 (YI03:0x0d08e2c1)
       INTEGER   MPCCI_QID_YI_03
       PARAMETER(MPCCI_QID_YI_03=X'0d08e2c1')

! Species mass fraction 04 (YI04:0x0e08e2c1)
       INTEGER   MPCCI_QID_YI_04
       PARAMETER(MPCCI_QID_YI_04=X'0e08e2c1')

! Species mass fraction 05 (YI05:0x0f08e2c1)
       INTEGER   MPCCI_QID_YI_05
       PARAMETER(MPCCI_QID_YI_05=X'0f08e2c1')

! Species mass fraction 06 (YI06:0x1008e2c1)
       INTEGER   MPCCI_QID_YI_06
       PARAMETER(MPCCI_QID_YI_06=X'1008e2c1')

! Species mass fraction 07 (YI07:0x1108e2c1)
       INTEGER   MPCCI_QID_YI_07
       PARAMETER(MPCCI_QID_YI_07=X'1108e2c1')

! Species mass fraction 08 (YI08:0x1208e2c1)
       INTEGER   MPCCI_QID_YI_08
       PARAMETER(MPCCI_QID_YI_08=X'1208e2c1')

! Species mass fraction 09 (YI09:0x1308e2c1)
       INTEGER   MPCCI_QID_YI_09
       PARAMETER(MPCCI_QID_YI_09=X'1308e2c1')


! Additional defines, not quantities!

       INTEGER   MPCCI_QID_UGS_COUNT
       PARAMETER(MPCCI_QID_UGS_COUNT=8)

       INTEGER   MPCCI_QID_UGV_COUNT
       PARAMETER(MPCCI_QID_UGV_COUNT=8)

       INTEGER   MPCCI_QID_YI_COUNT
       PARAMETER(MPCCI_QID_YI_COUNT=10)
